# escape=`

FROM lacledeslan/gamesvr-srcds-7daystodie:linux

MAINTAINER Laclede's LAN <contact@lacledeslan.com>

ENV IMAGE_NAME="gamesvr-srcds-7daystodie-freeplay:linux"

USER root

COPY ./dist /app/bin/

RUN usermod -l 7DaysToDieFreeplay 7DaysToDie

USER 7DaysToDieFreeplay