# escape=`

FROM lacledeslan/gamesvr-7daystodie

LABEL maintainer "Laclede's LAN <contact@lacledeslan.com>"

ENV IMAGE="gamesvr-7daystodie-freeplay:linux"

HEALTHCHECK NONE

# UPDATE USERNAME
RUN usermod -l 7DaysToDieFreeplay 7DaysToDie

USER 7DaysToDieFreeplay

COPY ./dist /app/

WORKDIR /app/