# escape=`

FROM lacledeslan/gamesvr-srcds-7daystodie:linux

LABEL maintainer "Laclede's LAN <contact@lacledeslan.com>"

ENV IMAGE="gamesvr-srcds-7daystodie-freeplay:linux"

HEALTHCHECK NONE

# UPDATE USERNAME
RUN usermod -l 7DaysToDieFreeplay 7DaysToDie

USER 7DaysToDieFreeplay

COPY ./dist /app/bin/

WORKDIR /app/bin/